In [1]:
import pandas as pd
import numpy as np

In [46]:
# Preparando o terreno

# Preparando o Toy DataSet:
"""

Criar um pequeno conjunto de dados artificial com cerca de 4 exemplos e 1 atributo.

    Isso significa que vamos ter um data set no seguinte formato:

        X       |       y
        1       |       10
        2       |       20
        3       |       30
        4       |       40


    Algo mais ou menos assim

O objetivo é validar se o algoritmo encontra uma solução correta com erro na ordem de 10⁻³.


Exemplo: y=x^2 

        X       |       y
        1       |       1
        2       |       4
        3       |       9
        4       |       16

    Vai ser essa função que vou fazer


"""

'\n\nCriar um pequeno conjunto de dados artificial com cerca de 4 exemplos e 1 atributo.\n\n    Isso significa que vamos ter um data set no seguinte formato:\n\n        X       |       y\n        1       |       10\n        2       |       20\n        3       |       30\n        4       |       40\n\n\n    Algo mais ou menos assim\n\nO objetivo é validar se o algoritmo encontra uma solução correta com erro na ordem de 10⁻³.\n\n\nExemplo: y=x^2 \n\n        X       |       y\n        1       |       1\n        2       |       4\n        3       |       9\n        4       |       16\n\n    Vai ser essa função que vou fazer\n\n\n'

In [3]:
"""def resolve_data_train(df:pd.DataFrame, output:str = '') -> np.array: 
     
    O que acontece é que: investigando a forma como eu devo mutiplicar os vetores de parâmetros pelos dados de entrada, encontrei problemas para realizar essa multiplicação. O que saia era algo assim:

        array([1, 1]) # x[0][:]
        array([1]) # x[0][0]

    Essa função recebe um dataframe de dados de entrada, com o nome da coluna de output, removemos ela e criamos um np.array, que é uma matriz, com as entradas por linhas, para sair assim:

        feature 0 ->  [1 2 3 4]
        feature 1 ->  [2 4 6 8]

    # Adicionei um parâmetro opcional, dado que alguns datasets podem conter o output fora dos dados de entrada. Além disso, preciso lembrar que a primeira "feature" é relacionada com o parâmetro
    theta 0, logo, precisa ser 1
    
    features= []
    
    features.append(np.ones(df.shape[0])) # Elementos que correspondem ao parâmetro 0 !

    for i in range(len(df.columns)):
        if output != df.columns[i]: # Aberto a otimização aqui
            features.append((np.transpose(df[df.columns[i]].to_numpy()))) # Elementos que correspondem ao parâmetro i

    return features
"""

'def resolve_data_train(df:pd.DataFrame, output:str = \'\') -> np.array: \n\n    O que acontece é que: investigando a forma como eu devo mutiplicar os vetores de parâmetros pelos dados de entrada, encontrei problemas para realizar essa multiplicação. O que saia era algo assim:\n\n        array([1, 1]) # x[0][:]\n        array([1]) # x[0][0]\n\n    Essa função recebe um dataframe de dados de entrada, com o nome da coluna de output, removemos ela e criamos um np.array, que é uma matriz, com as entradas por linhas, para sair assim:\n\n        feature 0 ->  [1 2 3 4]\n        feature 1 ->  [2 4 6 8]\n\n    # Adicionei um parâmetro opcional, dado que alguns datasets podem conter o output fora dos dados de entrada. Além disso, preciso lembrar que a primeira "feature" é relacionada com o parâmetro\n    theta 0, logo, precisa ser 1\n\n    features= []\n\n    features.append(np.ones(df.shape[0])) # Elementos que correspondem ao parâmetro 0 !\n\n    for i in range(len(df.columns)):\n        if o

# Fórmula dos gradiente dos mínimos quadradados para múltiplos atributos:

- Função de custo
$$J(\theta) = \frac{1}{2m} \sum_{i=1}^m (h_\theta(x^{(i)}) - y_i)^2$$

- Gradiente descedente para múltiplos atributos:

$$\theta _j := \theta _j - \alpha \frac{\partial}{\partial \theta _j} J(\theta)$$

# Como funciona

$\theta ^T$ = $\begin{bmatrix}\theta _0 & \theta _1 & \theta_2 & ... & \theta _n \end{bmatrix}_{1xn}$ 

x = $\begin{bmatrix} x_0\\ x_1  \\ ...  \\ x_n \end{bmatrix}_{nx1}$

Ou seja, cada linha corresponde a uma feature.

Onde a quantidade de colunas de j determinarão a quantidade de "predições" feitas pelo modelo, dado que a multiplicação de $\theta ^T$ * x vai ser dada por:

$ \theta ^T * x $ = $ \theta _0 * x_0 + \theta _1 * x_1 + ... + \theta _n * x_n $

- Com as dimensões de x sendo $x_{nx2}$, teríamos algo como:

$ \theta ^T * x $ = $\begin{bmatrix} \theta _0 * x_0^0 + \theta _1 * x_1^0 + ... + \theta _n * x_n^0 & \theta _0 * x_0^1 + \theta _1 * x_1^1 + ... + \theta _n * x_n^1  \end{bmatrix}_{1x2}$


In [47]:
dado_sintetico = {"input": [1,2,3,4], "output":[1,4.1,9,16]}
df_s = pd.DataFrame(data=dado_sintetico)
df_s

,input,output
0,1,1.0
1,2,4.1
2,3,9.0
3,4,16.0


In [64]:
np.ones((df_s.to_numpy()).shape[0])

array([1., 1., 1., 1.])

In [66]:
np.transpose(df_s.to_numpy())

array([[ 1. ,  2. ,  3. ,  4. ],
       [ 1. ,  4.1,  9. , 16. ]])

In [ ]:

x = np.append(
        [np.ones((df_s.to_numpy()).shape[0])], 
        np.transpose(df_s.to_numpy()),
        axis=0 # para entrar como uma feature
    )
x # Pronto, agora temos que cada linha corresponde a uma feature, em cada entrada da iteração

array([[ 1. ,  1. ,  1. ,  1. ],
       [ 1. ,  2. ,  3. ,  4. ],
       [ 1. ,  4.1,  9. , 16. ]])

In [72]:
parametros = np.ones(x.shape[0])
parametros

array([1., 1., 1.])

In [ ]:
parametros@x # aqui cada saída corresponde a um output de y

array([ 3. ,  7.1, 13. , 21. ])

In [ ]:
# Um detalhe, nós temos que o theta0 é um termo indepentente, ou seja, a entrada dele é sempre com o 1. portanto, precisamos "adicionar" uma feature que tenha sempre o valor 1

In [8]:
# TODO: Travar o retorno das funções, implementar a regressão linear para multi-atributos, adicionar o erro para convergir lá

class RTrainer:
    # Etapa de treinamento, é a mais simples, implementação está no slide
    def __init__(self):
        """Função que iniciliza o nosso objeto da classe RTrainer"""
            
        # TODO: adicionar hiperparâmetros:
            # TODO: taxa de aprendizado, quantidade de iterações

        

        # Possivelmente vamos ter que adicionar algum parâmetro ajustável do erro mínimo ali da função de custo
        # E também devemos precisar adicionar o parâmetro da quantidade de processamentos que vamos fazer
        pass

    # vou ver se travo isso como um array numpy
    def fit(self, dados_entrada):

        # Antes de começar, preciso pensar: "Essa função precisa ser modular, isto é, funcionar para uma quantidade n qualquer de features passadas"


        # Vetor de parâmetros/pesos

        # TODO: Tirar daqui, por em init, e adicionar uma função de deixar aleatório/começando em 0
        parametros = np.zeros(dados_entrada.ndim) # 0 vai ser o chute inicial dos meus parâmetros


        y_pred = 0 # TODO: validar, acho que isso vai virar um inteiro e não um vetor

        # Função -> h(x) = theta0*1 + theta1*x1 + ... thetan*xn, nos dá y_pred = ^y
        # 
        for i in range(len(parametros)):
            y_pred += parametros[i]*dados_entrada[i]

        
        # Erro médio por iteração:
        print("Erro médio -> ", 1/(len(dados_entrada[0])) * np.sum((y_pred - y)**2))

        # Atualizando 

        features = np.zeros(0)

        

        # ver como eu vou juntar esses parâmetros com os dados de entrada p ficar certinho -> theta0 + theta1*x1 + theta2*x2 + ... + thetan*xn
        """ Método que realiza o treinamento do modelo """

        
        # Estava pensando que seria só o uso da implementação base, mas não, precisa ser a multi-atributos -> tem no slide
        pass
    
    # Entender como posso fazer isso aqui
    def predict(self):
        """Método que realiza previsão do modelo, vai retornar -> um vetor de parâmetros OU um objeto MODEL contendo ao menos uma propriedade que indique o número de parâmetros"""
        pass