In [3]:
import pandas as pd
import numpy as np

In [117]:
# Preparando o terreno

# Preparando o Toy DataSet:
"""

Criar um pequeno conjunto de dados artificial com cerca de 4 exemplos e 1 atributo.

    Isso significa que vamos ter um data set no seguinte formato:

        X       |       y
        1       |       10
        2       |       20
        3       |       30
        4       |       40


    Algo mais ou menos assim

O objetivo é validar se o algoritmo encontra uma solução correta com erro na ordem de 10⁻³.


Exemplo: y=x^2 

        X       |       y
        1       |       1
        2       |       4
        3       |       9
        4       |       16

    Vai ser essa função que vou fazer


"""

dado_sintetico = {"input": [1,2,3,4], "output":[1,4.1,9,16]}
df_s = pd.DataFrame(data=dado_sintetico)
df_s

,input,output
0,1,1.0
1,2,4.1
2,3,9.0
3,4,16.0


In [118]:
df_s.shape[1]

2

In [119]:
X_features.ndim

2

In [120]:
x = X_features[:]
x[:][0]

array([1, 1])

In [121]:
feature = []
feature.append(np.transpose(x[0])) # mas o problema é como vou multiplicar isso pelo ngc
print(x[0])
print(feature)
feature.append(np.transpose(x[0]*2))
print(x[0]*2)
print("feature 0 -> ", np.array(feature[0]))
print("feature 1 -> ", feature[1])

type(feature[1]) # -> está saindo um np.array

# acredito que dessa forma está ótimo na real

[1 1]
[array([1, 1])]
[2 2]
feature 0 ->  [1 1]
feature 1 ->  [2 2]


numpy.ndarray

In [122]:
# Preciso lembrar que: o número de parâmetros é n, e o número de entrada é n-1, como eu resolvo?
    # Inserindo uma lista com o mesmo número de elementos, dos dados de entrada, só que de 1's

In [123]:
x = np.array(1)
x = (np.append(1, df_s['input'].to_numpy()))
x

array([1, 1, 2, 3, 4])

In [124]:
df_s.shape

(4, 2)

In [125]:
for i in range(len(df_s.columns)):
    print(i)
    print(df_s.columns[i])


0
input
1
output


In [ ]:
def resolve_data_train(df:pd.DataFrame, output:str = '') -> np.array: 
    """ 
    O que acontece é que: investigando a forma como eu devo mutiplicar os vetores de parâmetros pelos dados de entrada, encontrei problemas para realizar essa multiplicação. O que saia era algo assim:

    array([1, 1]) # x[0][:]
    array([1]) # x[0][0]


    Essa função recebe um dataframe de dados de entrada, com o nome da coluna de output, removemos ela e criamos um np.array, que é uma matriz, com as entradas por linhas, para sair assim:

    feature 0 ->  [1 2 3 4]
    feature 1 ->  [2 4 6 8]

    # Adicionei um parâmetro opcional, dado que alguns datasets podem conter o output fora dos dados de entrada
    """

    # Começando com o caso onde o output é dado no mesmo dataframe
        # Nesse caso precisamos subtrair por 1 a quantidade de colunas de x

        
    features = []
    
    features.append(np.ones(df.shape[0])) # Elementos que correspondem ao parâmetro 0

    for i in range(len(df.columns)):
        if output != df.columns[i]: # Aberto a otimização aqui
            features.append((np.transpose(df[df.columns[i]].to_numpy()))) # Elementos que correspondem ao parâmetro i

    return features
    


In [135]:
x = resolve_data_train(df_s, 'output')
for i in range(len(x)):
    print(x[i])

[1. 1. 1. 1.]
[1 2 3 4]


In [ ]:
# TODO: Travar o retorno das funções, implementar a regressão linear para multi-atributos, adicionar o erro para convergir lá

class RTrainer:
    # Etapa de treinamento, é a mais simples, implementação está no slide
    def __init__(self):
        """Função que iniciliza o nosso objeto da classe RTrainer"""
            
        # TODO: adicionar hiperparâmetros:
            # TODO: taxa de aprendizado, quantidade de iterações

        

        # Possivelmente vamos ter que adicionar algum parâmetro ajustável do erro mínimo ali da função de custo
        # E também devemos precisar adicionar o parâmetro da quantidade de processamentos que vamos fazer
        pass

    # vou ver se travo isso como um array numpy
    def fit(self, dados_entrada):

        # Antes de começar, preciso pensar: "Essa função precisa ser modular, isto é, funcionar para uma quantidade n qualquer de features passadas"


        # Vetor de parâmetros/pesos
        parametros = np.zeros(dados_entrada.ndim) # 0 vai ser o chute inicial dos meus parâmetros

        y_pred = 0

        for i in range(len(parametros)):
            y_pred += parametros[i]*dados_entrada[i]

        
        # Função
            # Vamos precisar fazer: h(x) = theta0*x0 + theta1*x1 + ... + thetan*xn
                # Problema: acho que da pra solucionar só colocando um vetor de 1's no x0, dessa forma não teria problema
                # Beleza, agora, como eu faço um multiplicador que relaciona as duas funções e fazemos o y_pred

        #y_pred =  

        features = np.zeros(0)

        

        # ver como eu vou juntar esses parâmetros com os dados de entrada p ficar certinho -> theta0 + theta1*x1 + theta2*x2 + ... + thetan*xn
        """ Método que realiza o treinamento do modelo """

        
        # Estava pensando que seria só o uso da implementação base, mas não, precisa ser a multi-atributos -> tem no slide
        pass
    
    # Entender como posso fazer isso aqui
    def predict(self):
        """Método que realiza previsão do modelo, vai retornar -> um vetor de parâmetros OU um objeto MODEL contendo ao menos uma propriedade que indique o número de parâmetros"""
        pass