In [41]:
import pandas as pd
import numpy as np

In [2]:
# Preparando o terreno

# Preparando o Toy DataSet:
"""

Criar um pequeno conjunto de dados artificial com cerca de 4 exemplos e 1 atributo.

    Isso significa que vamos ter um data set no seguinte formato:

        X       |       y
        1       |       10
        2       |       20
        3       |       30
        4       |       40


    Algo mais ou menos assim

O objetivo é validar se o algoritmo encontra uma solução correta com erro na ordem de 10⁻³.


Exemplo: y=x^2 

        X       |       y
        1       |       1
        2       |       4
        3       |       9
        4       |       16

    Vai ser essa função que vou fazer


"""

'\n\nCriar um pequeno conjunto de dados artificial com cerca de 4 exemplos e 1 atributo.\n\n    Isso significa que vamos ter um data set no seguinte formato:\n\n        X       |       y\n        1       |       10\n        2       |       20\n        3       |       30\n        4       |       40\n\n\n    Algo mais ou menos assim\n\nO objetivo é validar se o algoritmo encontra uma solução correta com erro na ordem de 10⁻³.\n\n\nExemplo: y=x^2 \n\n        X       |       y\n        1       |       1\n        2       |       4\n        3       |       9\n        4       |       16\n\n    Vai ser essa função que vou fazer\n\n\n'

In [3]:
"""def resolve_data_train(df:pd.DataFrame, output:str = '') -> np.array: 
     
    O que acontece é que: investigando a forma como eu devo mutiplicar os vetores de parâmetros pelos dados de entrada, encontrei problemas para realizar essa multiplicação. O que saia era algo assim:

        array([1, 1]) # x[0][:]
        array([1]) # x[0][0]

    Essa função recebe um dataframe de dados de entrada, com o nome da coluna de output, removemos ela e criamos um np.array, que é uma matriz, com as entradas por linhas, para sair assim:

        feature 0 ->  [1 2 3 4]
        feature 1 ->  [2 4 6 8]

    # Adicionei um parâmetro opcional, dado que alguns datasets podem conter o output fora dos dados de entrada. Além disso, preciso lembrar que a primeira "feature" é relacionada com o parâmetro
    theta 0, logo, precisa ser 1
    
    features= []
    
    features.append(np.ones(df.shape[0])) # Elementos que correspondem ao parâmetro 0 !

    for i in range(len(df.columns)):
        if output != df.columns[i]: # Aberto a otimização aqui
            features.append((np.transpose(df[df.columns[i]].to_numpy()))) # Elementos que correspondem ao parâmetro i

    return features
"""

'def resolve_data_train(df:pd.DataFrame, output:str = \'\') -> np.array: \n\n    O que acontece é que: investigando a forma como eu devo mutiplicar os vetores de parâmetros pelos dados de entrada, encontrei problemas para realizar essa multiplicação. O que saia era algo assim:\n\n        array([1, 1]) # x[0][:]\n        array([1]) # x[0][0]\n\n    Essa função recebe um dataframe de dados de entrada, com o nome da coluna de output, removemos ela e criamos um np.array, que é uma matriz, com as entradas por linhas, para sair assim:\n\n        feature 0 ->  [1 2 3 4]\n        feature 1 ->  [2 4 6 8]\n\n    # Adicionei um parâmetro opcional, dado que alguns datasets podem conter o output fora dos dados de entrada. Além disso, preciso lembrar que a primeira "feature" é relacionada com o parâmetro\n    theta 0, logo, precisa ser 1\n\n    features= []\n\n    features.append(np.ones(df.shape[0])) # Elementos que correspondem ao parâmetro 0 !\n\n    for i in range(len(df.columns)):\n        if o

# Fórmula dos gradiente dos mínimos quadradados para múltiplos atributos:

- Função de custo
$$J(\theta) = \frac{1}{2m} \sum_{i=1}^m (h_\theta(x^{(i)}) - y_i)^2$$

- Gradiente descedente para múltiplos atributos:

$$\theta _j := \theta _j - \alpha \frac{\partial}{\partial \theta _j} J(\theta)$$

# Como funciona

$\theta ^T$ = $\begin{bmatrix}\theta _0 & \theta _1 & \theta_2 & ... & \theta _n \end{bmatrix}_{1xn}$ 

x = $\begin{bmatrix} x_0\\ x_1  \\ ...  \\ x_n \end{bmatrix}_{nx1}$

Ou seja, cada linha corresponde a uma feature.

Onde a quantidade de colunas de j determinarão a quantidade de "predições" feitas pelo modelo, dado que a multiplicação de $\theta ^T$ * x vai ser dada por:

$ \theta ^T * x $ = $ \theta _0 * x_0 + \theta _1 * x_1 + ... + \theta _n * x_n $

- Com as dimensões de x sendo $x_{nx2}$, teríamos algo como:

$ \theta ^T * x $ = $\begin{bmatrix} \theta _0 * x_0^0 + \theta _1 * x_1^0 + ... + \theta _n * x_n^0 & \theta _0 * x_0^1 + \theta _1 * x_1^1 + ... + \theta _n * x_n^1  \end{bmatrix}_{1x2}$


In [4]:
dado_sintetico = {"input": [1,2,3,4], "output":[1,4.1,9,16]}
df_s = pd.DataFrame(data=dado_sintetico)
df_s

,input,output
0,1,1.0
1,2,4.1
2,3,9.0
3,4,16.0


In [5]:
np.ones((df_s.to_numpy()).shape[0])

array([1., 1., 1., 1.])

In [6]:
np.transpose(df_s.to_numpy())

array([[ 1. ,  2. ,  3. ,  4. ],
       [ 1. ,  4.1,  9. , 16. ]])

In [ ]:

x = np.append(
        [np.ones((df_s.to_numpy()).shape[0])], # Precisa ser uma "linha" para não desfazer a configuração da matriz, esse aqui é a feature x0, ou seja, 1
        np.transpose(df_s.to_numpy()), 
        axis=0 # Garantindo que entre como uma linha
    )
x # Pronto, agora temos que cada linha corresponde a uma feature, em cada entrada da iteração

array([[ 1. ,  1. ,  1. ,  1. ],
       [ 1. ,  2. ,  3. ,  4. ],
       [ 1. ,  4.1,  9. , 16. ]])

In [8]:
parametros = np.ones(x.shape[0])
parametros

array([1., 1., 1.])

In [14]:
teste = parametros@x # aqui cada saída corresponde a um output de y
teste

array([ 3. ,  7.1, 13. , 21. ])

In [ ]:
y = df_s['output'].to_numpy()
teste - y # certinho!

array([2., 3., 4., 5.])

In [19]:
len(x[0])

4

In [29]:
print(x[1])

[1. 2. 3. 4.]


In [36]:
x[0]*14

array([14., 14., 14., 14.])

In [38]:
print(np.sum((teste - y) * x[i]))

130.3


In [53]:
# Um detalhe, nós temos que o theta0 é um termo indepentente, ou seja, a entrada dele é sempre com o 1. portanto, precisamos "adicionar" uma feature que tenha sempre o valor 1

parametros_temp = parametros.copy()
print(parametros_temp)

for i in range(len(parametros)):
    print((1/(len(x[0]))), " * ", (np.sum(teste - y), " * ", x[i]))
    parametros_temp[i] = parametros[i] - 0.001 * (1/(len(x[0]))) * np.sum((teste - y) * x[i] )

parametros = parametros_temp
print(parametros)

[0.9825   0.95     0.837125]
0.25  *  (np.float64(14.0), ' * ', array([1., 1., 1., 1.]))
0.25  *  (np.float64(14.0), ' * ', array([1., 2., 3., 4.]))
0.25  *  (np.float64(14.0), ' * ', array([ 1. ,  4.1,  9. , 16. ]))
[0.979   0.94    0.80455]


In [45]:
x.shape

(3, 4)

In [ ]:
# TODO: Travar o retorno das funções, implementar a regressão linear para multi-atributos, adicionar o erro para convergir lá

class RTrainer:
    # Etapa de treinamento, é a mais simples, implementação está no slide
    def __init__(self, a, ephocs, erro=0, logger=False):
        """Construtor da classe RTrainer"""
            
        self.a = a # Taxa de aprendizado
        self.ephocs = ephocs # Quantidade de iterações do modelo
        self.erro = erro # Erro mínimo, um parâmetro adicional na hora de iterar, opcional
        self.logger = logger
        
    def fit(self, dados_entrada: pd.DataFrame) -> np.ndarray:
        """ Método que realiza o treinamento do modelo """

        # Antes de começar o treinamento, vamos primeiro modelar os dados de forma a facilitar o próprio

        x = np.append(
                [np.ones((dados_entrada.to_numpy()).shape[0])], # O shape é para preencher com a quantidade de dados de entrada que temos nas outras features, esse aqui é o x0 -> vetor de 1s
                np.transpose(dados_entrada.to_numpy()),  # Necessário transpor porque cada linha fica como uma feature
                axis=0 # Garantindo que vamos manter uma estrutura de: cada linha é uma feature, e cada coluna é uma entrada que resulta nos dados de treinamento, que acaba sendo o contrário do que temos no slide
            )

        # Ok, temos a matriz dos dados de entrada, agora precisamos criar os parâmetros

        parametros = np.ones(x.shape[0]) # TODO: adicionar um parâmetro opcional que possa definir o tipo de inicialização desse vetor de parâmetros, se é rand, 0 e 1, vai ser um if né simples
        parametros_temp = parametros.copy()

        # Agora podemos realizar as predições
        for i in range(self.ephocs):
            # Primeiro, precisamos calcular o vetor y_pred, que vai ser uma multiplicação de matrizes

            y_pred = parametros @ x # O "@" é o operador de multiplicação de matrizes do numpy

            # Segundo, calculando a função de custo
            
            custo = 1/len(x[0]) * np.sum((y_pred - y)**2) # Só se quisermos ver o comportamento do custo, mas não é necessário essa linha aqui

            # Loggar as coisas, mas com um limitante para não ser chato
            if self.logger and (self.ephocs%10 == 0):
                print("Custo -> ", custo)

            # Terceiro, aplicando o método do gradiente descendente para múltiplos atributos

            for j in range(len(x.shape[0])): 
                # Iterando por feature
                parametros_temp[i] = parametros[i] - self.a * (1/(len(x[0]))) * np.sum((teste - y) * x[i])

            parametros = parametros_temp

        return parametros


    # Entender como posso fazer isso aqui
    def predict(self):
        """Método que realiza previsão do modelo, vai retornar -> um vetor de parâmetros OU um objeto MODEL contendo ao menos uma propriedade que indique o número de parâmetros"""
        pass